export const mockData ={
	"data":[
		{
			"beginDate":"2018-01-11 00:00:00",
			"newsPublishName":"玩事文化",
			"seq":1,
			"title":"标题：“玩事·一站到底”决赛名单出炉！",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/names.jpg"
		},
		{
			"beginDate":"2017-12-06",
			"newsPublishName":"玩事文化",
			"seq":1,
			"title":"标题：“玩事·一站到底”决赛名单出炉！20位小伙伴成功进阶决赛",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/banner.jpg"
		},
		{
			"beginDate":"2017-12-06",
			"newsPublishName":"玩事文化",
			"seq":6,
			"title":"标题：“玩事·一站到底”决赛名单出炉！",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/names.jpg"
		},
		{
			"beginDate":"2017-12-05",
			"newsPublishName":"玩事文化",
			"seq":2,
			"title":"标题：“玩事·一站到底”决赛名单出炉！20位小伙伴成功进阶决赛",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/banner.jpg"
		},
		{
			"beginDate":"2017-12-04",
			"newsPublishName":"玩事文化",
			"seq":3,
			"title":"标题：“玩事·一站到底”决赛名单出炉！20位小伙伴成功进阶决赛",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/names.jpg"
		},
		{
			"beginDate":"2017-12-03",
			"newsPublishName":"玩事文化",
			"seq":4,
			"title":"标题：“玩事·一站到底”决赛名单出炉！",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/names.jpg"
		},
		{
			"beginDate":"2017-12-02",
			"newsPublishName":"玩事文化",
			"seq":5,
			"title":"标题：“玩事·一站到底”决赛名单出炉！",
			"url":"https://hongbao-cdn.yonyoucloud.com/uculture/app/html/interview/20171204/names.jpg"
		}
	],
	"flag":0
}
